Repository mediar-ai/screenpipe, pull requests merged in 2025-03, with the labels that each got.

#1518 fix dev cli encoding issue
  screenpipe-js/cli/bun.lockb
  screenpipe-js/cli/dist/index.js
  screenpipe-js/cli/package.json
Labels: 🙋 Bounty claim

#1465 feat: support deepgram audio queries and fix streaming in openai structured outputs
  screenpipe-js/ai-proxy/src/handlers/chat.ts
  screenpipe-js/ai-proxy/src/handlers/models.ts
  screenpipe-js/ai-proxy/src/handlers/transcription.ts
  screenpipe-js/ai-proxy/src/handlers/voice-ws.ts
  screenpipe-js/ai-proxy/src/handlers/voice.ts
  screenpipe-js/ai-proxy/src/index.ts
  screenpipe-js/ai-proxy/src/providers/openai.ts
  screenpipe-js/ai-proxy/src/services/analytics.ts
  screenpipe-js/ai-proxy/src/services/deepgram.ts
  screenpipe-js/ai-proxy/src/types.ts
  screenpipe-js/ai-proxy/src/utils/auth.ts
  screenpipe-js/ai-proxy/src/utils/cors.ts
  screenpipe-js/ai-proxy/src/utils/rate-limiter.ts
  screenpipe-js/ai-proxy/src/utils/subscription.ts
  screenpipe-js/ai-proxy/src/utils/voice-utils.ts
Labels: 💎 Bounty

#1471 Export frames as video
  pipes/rewind/src/app/layout.tsx
  pipes/rewind/src/components/export-button.tsx
  pipes/rewind/src/components/timeline/ai-panel.tsx
  pipes/rewind/src/components/timeline/timeline-dock-section.tsx
  pipes/rewind/src/components/timeline/timeline-selection.tsx
  pipes/rewind/src/components/timeline/timeline.tsx
  pipes/rewind/src/lib/hooks/use-timeline-selection.tsx
  screenpipe-app-tauri/src-tauri/tauri.conf.json
  screenpipe-server/src/server.rs
  screenpipe-server/src/video_utils.rs
Labels: 🙋 Bounty claim

#1541 dev pipe publish prebuild
  screenpipe-js/cli/dist/index.js
  screenpipe-js/cli/src/commands/pipe/publish.ts
Labels: 🙋 Bounty claim

#1557 add deb to supported targets
  screenpipe-app-tauri/src-tauri/tauri.conf.json
Labels: needs-more-info

#1585 fix windows build
  screenpipe-core/src/operator/platforms/mod.rs
Labels: needs-more-info

#1592 make screenpipe run on Windows 10
  .github/workflows/release-app.yml
  .github/workflows/release-cli.yml
  .github/workflows/windows-integration-test.yml
Labels: needs-more-info

#1596 fix build And windows integration test
  Cargo.toml
  screenpipe-app-tauri/lib/hooks/use-settings.tsx
  screenpipe-server/src/cli.rs
Labels: needs-more-info

#1597 Add vcredist setup to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs-more-info

#1614 fix: search filter generator not working
  pipes/search/src/components/search-filter-generator.tsx
Labels: needs-more-info

#1616 fix: `test-linux` now work on github codespaces
  .devcontainer/scripts/linux_integration.sh
Labels: needs-more-info
