Repository mediar-ai/screenpipe, pull requests merged in 2025-05, with the labels that each got.

#1748 fix: screenpipe not working due to IPv6 port and wrong design flow
  .github/scripts/check_logs.sh
  screenpipe-app-tauri/src-tauri/src/main.rs
  screenpipe-server/src/bin/screenpipe-server.rs
Labels: 🙋 Bounty claim

#1744 fix: CONTRIBUTING.md - windows part
  CONTRIBUTING.md
  screenpipe-app-tauri/scripts/pre_build.js
Labels: needs-more-info

#1641 fix: ship with ffmpeg
  screenpipe-app-tauri/.gitignore
  screenpipe-app-tauri/scripts/pre_build.js
  screenpipe-app-tauri/src-tauri/tauri.macos.conf.json
  screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
Labels: 🙋 Bounty claim

#1704 Improve notion pipe
  pipes/notion/bun.lockb
  pipes/notion/package.json
  pipes/notion/src/app/api/intelligence/route.ts
  pipes/notion/src/app/api/log/route.ts
  pipes/notion/src/components/ai-presets-selector.tsx
  pipes/notion/src/components/file-suggest-textarea.tsx
  pipes/notion/src/components/notion-settings.tsx
  pipes/notion/src/components/notion-url-to-input.tsx
  pipes/notion/src/lib/actions/update-pipe-config.ts
  pipes/notion/src/lib/helpers.ts
  pipes/notion/src/lib/hooks/use-pipe-settings.ts
  pipes/notion/src/lib/hooks/use-pipe-settings.tsx
  pipes/notion/src/lib/hooks/use-settings.ts
  pipes/notion/src/lib/notion/notion.ts
  pipes/notion/src/lib/store/settings-store.ts
  pipes/notion/src/lib/types.ts
Labels: 🙋 Bounty claim

#1780 fix model download ux
  screenpipe-app-tauri/components/model-download-tracker.tsx
  screenpipe-audio/src/transcription/whisper/model.rs
Labels: 🙋 Bounty claim

#1766 feat(testing): add e2e test for windows and linux
  .devcontainer/Dockerfile
  .github/scripts/setup_display.sh
  .github/workflows/e2e-test.yml
  .github/workflows/windows-integration-test.yml
  screenpipe-app-tauri/.mocharc.js
  screenpipe-app-tauri/bun.lockb
  screenpipe-app-tauri/components/screenpipe-status.tsx
  screenpipe-app-tauri/components/ui/badge.tsx
  screenpipe-app-tauri/e2e/record.js
  screenpipe-app-tauri/e2e/terminator-e2e/mocha.global.js
  screenpipe-app-tauri/e2e/terminator-e2e/screenpipe.spec.js
  screenpipe-app-tauri/e2e/tests/health-check.js
  screenpipe-app-tauri/e2e/utils.js
  screenpipe-app-tauri/e2e/videos/.keep
  screenpipe-app-tauri/package.json
  screenpipe-app-tauri/tsconfig.json
  screenpipe-app-tauri/wdio.conf.js
Labels: 🙋 Bounty claim, 💰 Rewarded

#1643 [linux] bundle tesseract and ffmpeg
  screenpipe-app-tauri/scripts/pre_build.js
  screenpipe-app-tauri/src-tauri/tauri.linux.conf.json
  screenpipe-core/src/ffmpeg.rs
Labels: needs-more-info
